'use client';
import { useState } from 'react';

export default function Dashboard() {
  const [installationId, setInstallationId] = useState('');

  const handleLink = (e: React.FormEvent) => {
    e.preventDefault();
    alert(`Linked installation ID: ${installationId}`);
    setInstallationId('');
  };

  const activityData = [
    { id: 1, campaign: 'AgentMonitor Pro', date: '2026-09-19', impressions: 45, earnings: '₹22.50' },
    { id: 2, campaign: 'CloudDeploy Fast', date: '2026-09-18', impressions: 120, earnings: '₹60.00' },
    { id: 3, campaign: 'DevSecOps Suite', date: '2026-09-17', impressions: 80, earnings: '₹40.00' },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Developer Dashboard</h1>

      {/* Overview Metrics */}
      <div className="grid grid-cols-1 gap-5 sm:grid-cols-4 mb-8">
        <div className="bg-white overflow-hidden shadow rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <dt className="text-sm font-medium text-gray-500 truncate">Total Earnings (₹)</dt>
            <dd className="mt-1 text-3xl font-semibold text-gray-900">₹1,245.50</dd>
          </div>
        </div>
        <div className="bg-white overflow-hidden shadow rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <dt className="text-sm font-medium text-gray-500 truncate">Monthly Earnings</dt>
            <dd className="mt-1 text-3xl font-semibold text-gray-900">₹320.00</dd>
          </div>
        </div>
        <div className="bg-white overflow-hidden shadow rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <dt className="text-sm font-medium text-gray-500 truncate">Sponsored Sessions</dt>
            <dd className="mt-1 text-3xl font-semibold text-gray-900">142</dd>
          </div>
        </div>
        <div className="bg-white overflow-hidden shadow rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <dt className="text-sm font-medium text-gray-500 truncate">Eligible Impressions</dt>
            <dd className="mt-1 text-3xl font-semibold text-gray-900">890</dd>
          </div>
        </div>
      </div>

      {/* Installation Linking Card */}
      <div className="bg-white shadow rounded-lg mb-8 p-6">
        <h2 className="text-lg font-medium text-gray-900 mb-4">Link Installation</h2>
        <p className="text-sm text-gray-500 mb-4">
          Enter your installation ID to claim offline earnings generated by your CLI plugin.
        </p>
        <form onSubmit={handleLink} className="flex gap-4">
          <input
            type="text"
            value={installationId}
            onChange={(e) => setInstallationId(e.target.value)}
            placeholder="e.g. inst_abc123"
            required
            className="block w-full max-w-md rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 px-3"
          />
          <button
            type="submit"
            className="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Link ID
          </button>
        </form>
      </div>

      {/* Recent Activity Table */}
      <div className="bg-white shadow rounded-lg mb-8">
        <div className="px-4 py-5 sm:px-6 border-b border-gray-200">
          <h3 className="text-lg leading-6 font-medium text-gray-900">Recent Activity</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Campaign</th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Impressions</th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Earnings (₹)</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {activityData.map((activity) => (
                <tr key={activity.id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{activity.campaign}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{activity.date}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{activity.impressions}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-green-600 font-medium">{activity.earnings}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4">
        <div className="flex">
          <div className="ml-3">
            <p className="text-sm text-yellow-700">
              <strong>Disclaimer:</strong> Earnings depend on eligible sponsorship impressions, campaign availability, and platform demand.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
